# Generated by Django 5.0.3 on 2024-04-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('agency_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('headline', models.CharField(max_length=255)),
                ('story_cat', models.CharField(max_length=100)),
                ('story_region', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('story_date', models.DateField()),
                ('story_details', models.TextField()),
            ],
        ),
    ]
