# Generated by Django 5.0.3 on 2024-04-02 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsAggregator', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 4, 2, 14, 28, 57, 794791)),
        ),
    ]
