# Generated by Django 5.0.3 on 2024-04-02 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsAggregator', '0003_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='id',
        ),
        migrations.AlterField(
            model_name='story',
            name='key',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 4, 2, 22, 26, 54, 518260)),
        ),
    ]
