# Generated by Django 5.0.3 on 2024-04-02 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsAggregator', '0004_remove_story_id_alter_story_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='key',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 4, 2, 22, 28, 28, 844561)),
        ),
    ]
