# Generated by Django 5.0.3 on 2024-04-12 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsAggregator', '0005_alter_story_key_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='story',
            name='headline',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_cat',
            field=models.CharField(choices=[('pol', 'politics'), ('art', 'Art'), ('tech', 'technology'), ('trivia', 'trivia news')], max_length=10),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_details',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_region',
            field=models.CharField(choices=[('uk', 'United Kingdom news'), ('eu', 'European news'), ('w', 'World news')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 4, 13, 1, 46, 13, 996823)),
        ),
    ]
