# Generated by Django 5.0.3 on 2024-04-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsAggregator', '0007_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directory',
            new_name='Agency',
        ),
    ]
