# Generated by Django 5.0.3 on 2024-04-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsAggregator', '0008_rename_directory_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='story_cat',
            field=models.CharField(choices=[('pol', 'politics'), ('art', 'Art'), ('tech', 'technology'), ('trivial', 'trivial news')], max_length=10),
        ),
    ]
