# Generated by Django 5.0.3 on 2024-04-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsAggregator', '0010_user_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
